const assert=require('node:assert/strict');
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const base=path.join(__dirname,'../web');
const ctx={window:{},AbortController,Map,Math};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(base,'interactive_map.js'),'utf8'),ctx);
const proto=ctx.window.CorporationAtlas.prototype;
let captures=[],focus=0;
const viewport={focus(){focus++},setPointerCapture(id){captures.push(['viewport',id])},classList:{add(){},remove(){}},getBoundingClientRect(){return {left:0,top:0}}};
const marker={setPointerCapture(id){captures.push(['marker',id])}};
const a=Object.assign(Object.create(proto),{viewport,points:new Map(),scale:2,tx:-100,ty:-100,width:400,height:300,closePicker(){},queueDraw(){}});
const event=(id,x,y,onMarker=false,type='pointermove')=>({pointerId:id,clientX:x,clientY:y,button:0,type,target:{closest(){return onMarker?marker:null}}});
a.down(event(1,100,100,true));assert.equal(captures[0][0],'marker');assert.equal(focus,0);
a.down(event(2,200,100));assert(a.moved);
a.move(event(2,250,100));assert.equal(a.scale,3);assert.equal(a.tx,-200);assert.equal(a.ty,-200);
a.up(event(2,250,100,false,'pointerup'));assert(a.moved);
a.move(event(1,120,110));assert.equal(a.tx,-180);assert.equal(a.ty,-190);
a.up(event(1,120,110,false,'pointerup'));assert.equal(a.points.size,0);assert(a.moved);
a.down(event(3,100,100,true));assert.equal(a.moved,false);
a.up(event(3,100,100,true,'pointerup'));assert.equal(a.moved,false,'stationary marker tap remains selectable');
a.down(event(4,100,100));a.up(event(4,100,100,false,'pointercancel'));assert(a.moved);assert.equal(a.points.size,0);
a.down(event(5,100,100));for(let x=101;x<=109;x++)a.move(event(5,x,100));assert(a.moved,'slow drag is not mistaken for a tap');
a.up(event(5,109,100,false,'lostpointercapture'));assert.equal(a.points.size,0);
let disabled=0;const handlers={};
const doc={hidden:false,addEventListener(type,fn){handlers[type]=fn}};
const window={Telegram:{WebApp:{isVersionAtLeast:v=>v==='7.7',disableVerticalSwipes(){disabled++}}},addEventListener(){}};
vm.runInNewContext(fs.readFileSync(path.join(base,'gestures_v30.js'),'utf8'),{window,document:doc,console,performance:{now:()=>100},Math});
assert.equal(disabled,1);
function touch(n,map){let prevented=false;handlers.touchmove({touches:Array(n),cancelable:true,target:{closest:()=>map},preventDefault(){prevented=true}});return prevented;}
assert(touch(2,false));assert(touch(1,true));assert.equal(touch(1,false),false,'normal scrolling preserved');
handlers.visibilitychange();assert.equal(disabled,2);
console.log('PASS: marker capture, pinch anchor, pinch-to-pan, tap recovery, cancellation, slow drag, Telegram bridge, scroll/zoom routing');
