/* Corporation 25 — fleet economy and icon-led interface. */
function gameIcon25(name,extra=''){
  const paths={check:'M5 12l4 4L19 6',chart:'M4 18l5-6 4 3 7-9M15 6h5v5',building:'M5 21V5h10v16M15 10h4v11M8 9h4M8 13h4M8 17h4',home:'M3 11l9-7 9 7M5 10v10h14V10M9 20v-6h6v6',money:'M12 3v18M16 7.5c0-2-1.5-3-4-3s-4 1.1-4 3 1.5 2.7 4 3 4 1.3 4 3-1.5 3-4 3-4-1-4-3',news:'M5 4h14v16H5zM8 8h8M8 12h8M8 16h5',up:'M12 19V5M6 11l6-6 6 6',target:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18M12 7v10M7 12h10',garage:'M3 10l9-6 9 6v11H3V10M7 21v-7h10v7M9 17h6',clock:'M12 4a8 8 0 1 0 0 16 8 8 0 0 0 0-16M12 8v5l3 2',spark:'M12 3l1.7 5.3L19 10l-5.3 1.7L12 17l-1.7-5.3L5 10l5.3-1.7L12 3'};
  return `<span class="game-icon25 ${extra}" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.spark}"/></svg></span>`;
}
function businessIcon24(id){
  const paths={coffee:'M5 7h12v7a5 5 0 0 1-5 5h-2a5 5 0 0 1-5-5V7ZM17 8h2a3 3 0 0 1 0 6h-2M8 3v1M12 3v1M4 22h15',taxi:'M4 15l2-6h12l2 6v4h-2M6 19H4v-4h16v4h-2M7 15h10M8 9l1-3h6l1 3M7 19a2 2 0 1 0 0-4M17 19a2 2 0 1 0 0-4',logistics:'M3 7h11v11H3V7M14 11h4l3 4v3h-7M6 20a2 2 0 1 0 0-4M18 20a2 2 0 1 0 0-4',factory:'M3 21V10l6 3V8l6 4V3h4l2 18H3M7 17h1M12 17h1M17 17h1',it:'M3 4h18v13H3M8 21h8M12 17v4M9 8l-3 3 3 3M15 8l3 3-3 3',finance:'M3 9l9-6 9 6H3M5 11v8M10 11v8M14 11v8M19 11v8M3 22h18',conglomerate:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18M3 12h18M12 3c-6 6-6 12 0 18M12 3c6 6 6 12 0 18'};
  return `<span class="business-icon24"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[id]||paths.finance}"/></svg></span>`;
}
function vehicleArt25(kind){
  const truck=['van','truck','refrigerated','semi'].includes(kind),semi=kind==='semi',van=kind==='van';
  if(!truck)return `<svg class="vehicle-art25" viewBox="0 0 118 44" aria-hidden="true"><path d="M13 29l7-13h18l10-7h27l13 7 15 4 4 9H13Z"/><path d="M43 16l9-6h21l9 6H43Z" class="glass"/><circle cx="33" cy="30" r="7"/><circle cx="87" cy="30" r="7"/><path d="M10 30h101"/></svg>`;
  return `<svg class="vehicle-art25" viewBox="0 0 138 48" aria-hidden="true"><path d="M7 10h${semi?'78':'83'}v27H7z"/><path d="M${semi?'85':'90'} 18h25l16 12v7H${semi?'85':'90'}z"/><path d="M${semi?'92':'97'} 21h13l9 9H${semi?'92':'97'}z" class="glass"/><circle cx="28" cy="38" r="7"/><circle cx="${semi?'76':'80'}" cy="38" r="7"/><circle cx="116" cy="38" r="7"/>${van?'<path d="M7 10l12-7h56l15 7"/>':''}</svg>`;
}
function duration25(sec){sec=Math.max(0,Math.ceil(Number(sec||0)));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),ss=sec%60;return h>0?`${h} ч ${String(m).padStart(2,'0')} мин ${String(ss).padStart(2,'0')} сек`:`${String(m).padStart(2,'0')} мин ${String(ss).padStart(2,'0')} сек`;}
function renderFleet25(b){
  const f=b.transport;if(!f)return '';
  const garageText=f.upgrading?`Строится: ${f.capacity} → ${f.next_capacity} мест`:`${f.occupied} из ${f.capacity} мест занято`;
  return `<section class="fleet25"><div class="fleet-head25"><div>${gameIcon25('garage')}<span>АВТОПАРК</span><strong>${garageText}</strong></div><b>${fmt(f.income)}/ч</b></div><div class="garage-track25"><i style="width:${Math.min(100,f.occupied/f.capacity*100)}%"></i></div>${f.upgrading?`<div class="garage-build25" data-fleet-until="${f.upgrade_finishes_at}">${gameIcon25('clock')} Расширение завершится через <b>${duration25(f.upgrade_seconds_left)}</b></div>`:`<button class="garage-upgrade25" ${f.maxed?'disabled':''} onclick="upgradeGarage25('${b.id}')">${gameIcon25('garage')}<span>${f.maxed?'Максимум — 100 мест':`Расширить до ${f.next_capacity} мест`}<small>${f.maxed?'Дальнейшее расширение недоступно':`${fmt(f.next_upgrade_cost)} · ${duration25(f.next_upgrade_duration)}`}</small></span></button>`}<div class="vehicle-list25">${f.vehicles.map(v=>`<article class="vehicle-row25"><div class="vehicle-visual25">${vehicleArt25(v.kind)}</div><div class="vehicle-copy25"><b>${escapeHTML(v.name)}</b><span>${fmt(v.cost)} · +${fmt(v.income)}/ч</span><small>В парке: ${v.quantity} · капитал ${fmt(v.capitalization)}</small></div><div class="vehicle-actions25"><button ${f.available<1?'disabled':''} onclick="buyFleetVehicle25('${b.id}','${v.id}')">Купить</button><button ${v.quantity<1?'disabled':''} onclick="sellFleetVehicle25('${b.id}','${v.id}')">Продать</button></div></article>`).join('')}</div></section>`;
}
renderBusinesses=function(){
  const cards=(state.businesses||[]).map(b=>{const owned=Boolean(b.owned||Number(b.level)>0),canBuy=Number(state.player.money)>=Number(b.purchase_cost||0);return `<article class="card business-card business-card25 ${b.transport?'transport-business25':''}"><div class="business-head25"><div class="business-title25">${businessIcon24(b.id)}<div><h3>${escapeHTML(b.name)}</h3><p>${escapeHTML(b.desc)}</p></div></div>${owned?`<span class="owned-badge25">${gameIcon25('check')} В портфеле</span>`:'<span class="new-badge24">Доступен</span>'}</div><div class="business-metrics25"><div><span>${owned?'Доход сейчас':'Доход после покупки'}</span><b>${fmt(owned?b.current_income:b.income_after_purchase)}/ч</b></div><div><span>Капитализация</span><b>${fmt(owned?b.capitalization:b.purchase_cost)}</b></div></div>${owned?(b.transport?renderFleet25(b):`<div class="business-upgrade-title">ТОЧКИ РОСТА</div><div class="upgrade-grid upgrade-grid25">${(b.upgrades||[]).map(u=>`<button class="upgrade-btn ${u.owned?'owned':''}" ${u.owned?'disabled':''} onclick="upgradeBusiness('${b.id}','${u.id}')"><span class="upgrade-check25">${u.owned?gameIcon25('check'):gameIcon25('up')}</span><b>${escapeHTML(u.name.replace(/^[^\p{L}\p{N}]+/u,''))}</b><small>${u.owned?'Готово':`+${u.income_bonus_percent}% дохода`}</small><strong>${u.owned?'Установлено':fmt(u.cost)}</strong></button>`).join('')}</div>`)+`<button class="sell-business" onclick="sellBusiness('${b.id}')">Продать за ${fmt(b.sell_price)}</button><div class="business-capitalization">При продаже возвращается 30% капитализации</div>`:`<button class="buy" ${canBuy?'':'disabled'} onclick="buyBusiness('${b.id}')">Купить за ${fmt(b.purchase_cost)}</button>`}</article>`;}).join('');
  document.querySelector('#content').innerHTML=`<section class="business-page25"><div class="section-top"><div><div class="eyebrow">ОПЕРАЦИОННЫЕ АКТИВЫ</div><h2>Мои компании</h2></div></div><div class="grid">${cards}</div></section>`;
};
async function buyFleetVehicle25(bid,vid){const b=state.businesses.find(x=>x.id===bid),v=b?.transport?.vehicles.find(x=>x.id===vid);if(!v)return;const max=Math.min(b.transport.available,Math.floor(Number(state.player.money)/Number(v.cost)));const raw=prompt(`Сколько машин купить?\nСвободных мест: ${b.transport.available}\nДоступно по балансу: ${max}`,'1');if(raw===null)return;const q=Number(raw);if(!Number.isInteger(q)||q<1||q>max){modal('Покупка',`Введите целое число от 1 до ${max}.`);return;}try{const r=await api(`/api/fleet/${bid}/vehicle/${vid}/buy`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:q})});state=r.state;renderHeader();renderBusinesses();}catch(e){modal('Не удалось купить',e.message)}}
async function sellFleetVehicle25(bid,vid){const b=state.businesses.find(x=>x.id===bid),v=b?.transport?.vehicles.find(x=>x.id===vid);if(!v?.quantity)return;const raw=prompt(`Сколько машин продать?\nВ парке: ${v.quantity}\nВозврат за одну: ${fmt(v.sell_price)}`,'1');if(raw===null)return;const q=Number(raw);if(!Number.isInteger(q)||q<1||q>v.quantity){modal('Продажа',`Введите целое число от 1 до ${v.quantity}.`);return;}try{const r=await api(`/api/fleet/${bid}/vehicle/${vid}/sell`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:q})});state=r.state;renderHeader();renderBusinesses();}catch(e){modal('Не удалось продать',e.message)}}
async function upgradeGarage25(bid){if(!confirm('Начать расширение автопарка? Стоимость сразу войдёт в капитализацию бизнеса.'))return;try{const r=await api(`/api/fleet/${bid}/garage/upgrade`,{method:'POST'});state=r.state;renderHeader();renderBusinesses();}catch(e){modal('Расширение не начато',e.message)}}
window.buyFleetVehicle25=buyFleetVehicle25;window.sellFleetVehicle25=sellFleetVehicle25;window.upgradeGarage25=upgradeGarage25;window.renderBusinesses=renderBusinesses;

renderRating=async function(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем рейтинг…</div>';try{const rows=await api('/api/rating');if(page!=='rating')return;ratingRows24=rows;const mine=rows.findIndex(p=>Number(p.user_id)===Number(state.player.user_id));c.innerHTML=`<section class="rating-page"><div class="section-top"><div><div class="eyebrow">ТАБЛИЦА ЛИДЕРОВ</div><h2>Рейтинг корпораций</h2></div><span class="rank-count">${rows.length} компаний</span></div><div class="rank-summary">${mine>=0?`Твоё место <strong>#${mine+1}</strong>`:'Твоей компании пока нет в рейтинге'}<span>По полной капитализации</span></div><div class="grid">${rows.map((p,i)=>`<button id="rank-${i}" class="card rank-button ${i===mine?'rank-mine':''}" onclick="openPlayerProfile(${Number(p.user_id)})"><div class="rank-num">${String(i+1).padStart(2,'0')}</div><div><h3>${escapeHTML(p.corp_name)}${i===mine?'<small>ТЫ</small>':''}</h3><p>${fmt(p.capital)}</p><small>Свободно ${fmt(p.money)}</small></div></button>`).join('')}</div><div class="rank-jump rank-jump25"><button onclick="jumpRating24(0)" aria-label="В начало рейтинга">${gameIcon25('up')}<span>Вверх</span></button><button onclick="jumpRating24(${mine})" ${mine<0?'disabled':''}>${gameIcon25('target')}<span>Я</span></button></div></section>`;requestAnimationFrame(()=>jumpRating24(mine,false));}catch(e){modal('Рейтинг',e.message)}};window.renderRating=renderRating;

renderPropertyCard=function(p){const segmentNames={economy:'Эконом',business:'Бизнес',vip:'VIP'},typeNames={apartment:'Квартира',house:'Дом'},vip=p.segment==='vip';return `<article class="card property-card property-card25 ${vip?'property-vip25':''}"><div class="property-image-wrap"><img src="${p.photo}" alt="${escapeHTML(p.name)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src=propertyFallbackImage({})"><div class="property-image-shade25"></div><div class="property-badges"><span class="segment-${p.segment||'economy'}">${segmentNames[p.segment]||'Эконом'}</span><span>${typeNames[p.property_type]||''}</span>${p.prestige?`<span>${p.prestige}</span>`:''}</div></div><div class="property-body"><div class="business-head"><div><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.description)}</p></div>${p.owned?`<b class="owned-badge25">${gameIcon25('check')} Куплено</b>`:''}</div>${p.benefits?`<div class="property-benefits25">${p.benefits.map(x=>`<span>${gameIcon25('spark')}${escapeHTML(x)}</span>`).join('')}</div>`:''}<div class="property-metrics"><div><span>${p.owned?'Рыночная стоимость':'Цена'}</span><b>${fmt(p.current_value)}</b></div><div><span>Аренда</span><b>${fmt(p.rent_hour)}/ч</b></div></div><div class="property-yield">Доходность: <b>${Number(p.hourly_yield_percent||0).toFixed(2)}% / ч</b></div>${p.owned?`<div class="property-growth">${gameIcon25('chart')} Капитализация: <b>${fmt(p.capitalization)}</b></div><div class="upgrade-grid upgrade-grid25">${p.upgrades.map(u=>`<button class="upgrade-btn ${u.owned?'owned':''}" ${u.owned?'disabled':''} onclick="upgradeProperty('${p.id}','${u.id}')"><span class="upgrade-check25">${u.owned?gameIcon25('check'):gameIcon25('up')}</span><b>${escapeHTML(u.name)}</b><small>${u.owned?'Готово':`+${u.income_bonus_percent}% аренды`}</small><strong>${u.owned?'Установлено':fmt(u.cost)}</strong></button>`).join('')}</div><button class="v20-property-sell" onclick="sellProperty('${p.id}')">Продать за ${fmt(p.sell_price)}</button>`:`<button class="buy" onclick="buyProperty('${p.id}')">Купить за ${fmt(p.purchase_price)}</button>`}</div></article>`};window.renderPropertyCard=renderPropertyCard;

renderStatistics=async function(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем статистику…</div>';try{const s=await api('/api/statistics');c.innerHTML=`<section class="stats-page"><article class="stats-card">${gameIcon25('money')}<span>Общая прибыль</span><b>${fmt(s.total_earned)}</b></article><article class="stats-card">${gameIcon25('chart')}<span>Общие расходы</span><b>${fmt(s.total_spent)}</b></article><article class="stats-card">${gameIcon25('building')}<span>Куплено бизнесов</span><b>${s.companies_bought}</b></article><article class="stats-card">${gameIcon25('home')}<span>Куплено недвижимости</span><b>${s.properties_bought}</b></article><section class="chart-card"><h2>${gameIcon25('chart')} Прибыль по дням</h2>${renderProfitChart(s.daily_profit||[])}</section></section>`}catch(e){modal('Ошибка',e.message)}};window.renderStatistics=renderStatistics;

const renderMarketNews25=async()=>{const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем новости рынка…</div>';try{const d=await api('/api/market-news');if(page!=='investments'||investmentView!=='news')return;const cards=(d.news||[]).map(n=>{const cls=n.sentiment==='good'?'v21-good':'v21-bad',label=n.sentiment==='good'?'ПОЗИТИВНЫЙ СИГНАЛ':'НЕГАТИВНЫЙ СИГНАЛ',reaction=n.applied?`<div class="v21-news-reaction ${cls}"><b>Изменение: ${Number(n.impact_percent)>=0?'+':''}${Number(n.impact_percent).toFixed(2)}%</b> · ${fmt(n.price_before)} → ${fmt(n.price_after)}</div>`:`<div class="v21-news-reaction ${cls}"><b>${label}</b> · котировка отреагирует через 2 минуты</div>`;return `<article class="v21-news-card"><div class="news-photo-frame25"><img class="v21-news-photo" src="${n.photo}" alt="${escapeHTML(n.company)}" loading="lazy" decoding="async"></div><div class="v21-news-body"><div class="v21-news-kicker"><span>CORPORATION JOURNAL · ${escapeHTML(n.symbol)}</span><span>${v21Date(n.published_at)}</span></div><h3>${escapeHTML(n.title)}</h3><p>${escapeHTML(n.article)}</p>${reaction}</div></article>`}).join('');c.innerHTML=`<section class="v21-news-page"><div class="v21-news-head"><div><div class="eyebrow">MARKET NEWS</div><h2>${gameIcon25('news')} Новости рынка</h2></div><button class="back-button" onclick="v21BackInvestments()">← Назад</button></div><div class="v21-news-next">Вымышленные события появляются нерегулярно. Сила реакции ограничена 10%.</div>${cards||'<div class="empty">Новостей пока нет.</div>'}</section>`;}catch(e){modal('Ошибка',e.message)}};renderMarketNews=renderMarketNews25;window.renderMarketNews=renderMarketNews25;

const investmentBase25=renderInvestments;renderInvestments=async function(){await investmentBase25();document.querySelectorAll('.v21-news-entry').forEach(b=>b.innerHTML=`${gameIcon25('news')}<span>Новости рынка</span><i>›</i>`);};window.renderInvestments=renderInvestments;

capGrid=function(b){return `<div class="v20-capital-grid"><article class="stats-card">${gameIcon25('money')}<span>Свободные деньги</span><b>${fmt(b.cash)}</b></article><article class="stats-card">${gameIcon25('building')}<span>Бизнесы</span><b>${fmt(b.businesses)}</b></article><article class="stats-card">${gameIcon25('chart')}<span>Акции</span><b>${fmt(b.stocks)}</b></article><article class="stats-card">${gameIcon25('money')}<span>Облигации</span><b>${fmt(b.bonds)}</b></article><article class="stats-card">${gameIcon25('home')}<span>Недвижимость</span><b>${fmt(b.real_estate)}</b></article></div>`};window.capGrid=capGrid;
openPlayerProfile=async function(id){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем профиль…</div>';try{const p=await api(`/api/player/${id}`),businesses=p.businesses?.length?p.businesses.map(b=>`<article class="profile-business"><div><h3>${escapeHTML(b.name)}</h3><p>${escapeHTML(b.description)}</p></div><b>ур. ${b.level}</b></article>`).join(''):'<div class="empty">Бизнесов пока нет.</div>';c.innerHTML=`<section class="profile-page"><button class="back-button" onclick="backToRating()">← Назад к рейтингу</button><article class="profile-header"><div class="eyebrow">ПРОФИЛЬ ИГРОКА</div><h2>${escapeHTML(p.player.corp_name)}</h2><p>${gameIcon25('spark')} Общий капитал: ${fmt(p.capital)}</p><p>${gameIcon25('money')} Свободные деньги: ${fmt(p.player.money)}</p><p>${gameIcon25('chart')} Автодоход: ${fmt(p.hourly_income)}/ч</p></article>${capGrid(p.capital_breakdown||{})}<section class="profile-businesses"><h2>${gameIcon25('building')} Бизнесы</h2>${businesses}</section></section>`}catch(e){modal('Ошибка',e.message)}};window.openPlayerProfile=openPlayerProfile;
renderTaxes=function(){const t=state?.taxes||{},u=Number(t.unpaid||0),b=Boolean(t.blocked);document.querySelector('#content').innerHTML=`<section class="tax-page"><article class="tax-hero ${b?'tax-blocked':''}"><div class="eyebrow">НАЛОГОВАЯ СИСТЕМА</div><h2>${gameIcon25(b?'clock':'money')} ${b?'Доход остановлен':'Налоги'}</h2><p>Налог — 5% с автоматического дохода, дивидендов, дохода по облигациям, аренды и прибыли от продажи акций.</p></article><article class="stats-card"><span>Неоплаченный налог</span><b>${fmt(u)}</b></article><article class="card tax-info">${u>0?(b?'Срок оплаты истёк. Весь пассивный доход остановлен.':`До остановки дохода: <b>${formatTaxTime(t.seconds_left)}</b>.`):'Задолженности нет.'}</article><button class="buy" ${u>0?'':'disabled'} onclick="payTaxes()">${u>0?`Оплатить ${fmt(u)}`:'Налогов к оплате нет'}</button></section>`};window.renderTaxes=renderTaxes;
const oldOpenCity25=openCity;openCity=function(id){oldOpenCity25(id);const h=document.querySelector('.realestate-page>h2');if(h){h.textContent=h.textContent.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,'').trim();h.insertAdjacentHTML('afterbegin',gameIcon25('home'));}};window.openCity=openCity;

function cleanEmojiText25(root){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes)n.nodeValue=n.nodeValue.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,'').replace(/\s{2,}/g,' ');}
cleanEmojiText25(document.body);new MutationObserver(records=>{for(const r of records)for(const node of r.addedNodes){if(node.nodeType===Node.TEXT_NODE)node.nodeValue=node.nodeValue.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,'');else if(node.nodeType===Node.ELEMENT_NODE)cleanEmojiText25(node);}}).observe(document.body,{subtree:true,childList:true});
