/* Corporation 26.2 — fleet economy and icon-led interface. */
function gameIcon25(name,extra=''){
  const paths={check:'M5 12l4 4L19 6',chart:'M4 18l5-6 4 3 7-9M15 6h5v5',building:'M5 21V5h10v16M15 10h4v11M8 9h4M8 13h4M8 17h4',home:'M3 11l9-7 9 7M5 10v10h14V10M9 20v-6h6v6',money:'M12 3v18M16 7.5c0-2-1.5-3-4-3s-4 1.1-4 3 1.5 2.7 4 3 4 1.3 4 3-1.5 3-4 3-4-1-4-3',news:'M5 4h14v16H5zM8 8h8M8 12h8M8 16h5',up:'M12 19V5M6 11l6-6 6 6',target:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18M12 7v10M7 12h10',garage:'M3 10l9-6 9 6v11H3V10M7 21v-7h10v7M9 17h6',clock:'M12 4a8 8 0 1 0 0 16 8 8 0 0 0 0-16M12 8v5l3 2',spark:'M12 3l1.7 5.3L19 10l-5.3 1.7L12 17l-1.7-5.3L5 10l5.3-1.7L12 3'};
  return `<span class="game-icon25 ${extra}" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.spark}"/></svg></span>`;
}
function businessIcon24(id){
  const paths={coffee:'M5 7h12v7a5 5 0 0 1-5 5h-2a5 5 0 0 1-5-5V7ZM17 8h2a3 3 0 0 1 0 6h-2M8 3v1M12 3v1M4 22h15',taxi:'M4 15l2-6h12l2 6v4h-2M6 19H4v-4h16v4h-2M7 15h10M8 9l1-3h6l1 3M7 19a2 2 0 1 0 0-4M17 19a2 2 0 1 0 0-4',logistics:'M3 7h11v11H3V7M14 11h4l3 4v3h-7M6 20a2 2 0 1 0 0-4M18 20a2 2 0 1 0 0-4',factory:'M3 21V10l6 3V8l6 4V3h4l2 18H3M7 17h1M12 17h1M17 17h1',it:'M3 4h18v13H3M8 21h8M12 17v4M9 8l-3 3 3 3M15 8l3 3-3 3',finance:'M3 9l9-6 9 6H3M5 11v8M10 11v8M14 11v8M19 11v8M3 22h18',conglomerate:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18M3 12h18M12 3c-6 6-6 12 0 18M12 3c6 6 6 12 0 18'};
  return `<span class="business-icon24"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[id]||paths.finance}"/></svg></span>`;
}
function vehicleArt25(kind){
  const truck=['van','truck','refrigerated','semi'].includes(kind),semi=kind==='semi',van=kind==='van';
  if(!truck)return `<svg class="vehicle-art25" viewBox="0 0 118 44" aria-hidden="true"><path d="M13 29l7-13h18l10-7h27l13 7 15 4 4 9H13Z"/><path d="M43 16l9-6h21l9 6H43Z" class="glass"/><circle cx="33" cy="30" r="7"/><circle cx="87" cy="30" r="7"/><path d="M10 30h101"/></svg>`;
  return `<svg class="vehicle-art25" viewBox="0 0 138 48" aria-hidden="true"><path d="M7 10h${semi?'78':'83'}v27H7z"/><path d="M${semi?'85':'90'} 18h25l16 12v7H${semi?'85':'90'}z"/><path d="M${semi?'92':'97'} 21h13l9 9H${semi?'92':'97'}z" class="glass"/><circle cx="28" cy="38" r="7"/><circle cx="${semi?'76':'80'}" cy="38" r="7"/><circle cx="116" cy="38" r="7"/>${van?'<path d="M7 10l12-7h56l15 7"/>':''}</svg>`;
}
function duration25(sec){sec=Math.max(0,Math.floor(Number(sec||0)));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),ss=sec%60;return h>0?`${h} ч ${String(m).padStart(2,'0')} мин ${String(ss).padStart(2,'0')} сек`:`${m} мин ${String(ss).padStart(2,'0')} сек`;}
let serverClock25={stamp:0,offsetMs:0};
function syncServerClock25(force=false){
  const serverMs=Number(state?.server_time_ms||0)||(Number(state?.server_time||0)*1000);
  if(serverMs>0&&(force||serverMs!==serverClock25.stamp))serverClock25={stamp:serverMs,offsetMs:serverMs-Date.now()};
}
function serverNow25(){syncServerClock25();return Date.now()+Number(serverClock25.offsetMs||0);}
function renderFleet25(b){
  const f=b.transport;if(!f)return '';
  const garageText=f.upgrading?`Строится: ${f.capacity} → ${f.next_capacity} мест`:`${f.occupied} из ${f.capacity} мест занято`;
  return `<section class="fleet25"><div class="fleet-head25"><div>${gameIcon25('garage')}<span>АВТОПАРК</span><strong>${garageText}</strong></div><b>${fmt(f.income)}/ч</b></div><div class="garage-track25"><i style="width:${Math.min(100,f.occupied/f.capacity*100)}%"></i></div>${f.upgrading?`<div class="garage-build25" data-live-until="${f.upgrade_finishes_at}" data-live-reload="businesses">${gameIcon25('clock')}<span class="garage-build-copy25"><span class="garage-build-label25">Расширение завершится через</span><b data-live-value>${duration25(f.upgrade_seconds_left)}</b></span></div>`:`<button class="garage-upgrade25" ${f.maxed?'disabled':''} onclick="upgradeGarage25('${b.id}')">${gameIcon25('garage')}<span>${f.maxed?'Максимум — 100 мест':`Расширить до ${f.next_capacity} мест`}<small>${f.maxed?'Дальнейшее расширение недоступно':`${fmt(f.next_upgrade_cost)} · ${duration25(f.next_upgrade_duration)}`}</small></span></button>`}<div class="vehicle-list25">${f.vehicles.map(v=>`<article class="vehicle-row25"><div class="vehicle-visual25">${vehicleArt25(v.kind)}</div><div class="vehicle-copy25"><b>${escapeHTML(v.name)}</b><span>${fmt(v.cost)} · +${fmt(v.income)}/ч</span><small>В парке: ${v.quantity} · капитал ${fmt(v.capitalization)}</small></div><div class="vehicle-actions25"><button ${f.available<1?'disabled':''} onclick="buyFleetVehicle25('${b.id}','${v.id}')">Купить</button><button ${v.quantity<1?'disabled':''} onclick="sellFleetVehicle25('${b.id}','${v.id}')">Продать</button></div></article>`).join('')}</div></section>`;
}
function businessCard28(b){const owned=Boolean(b.owned||Number(b.level)>0),canBuy=Number(state.player.money)>=Number(b.purchase_cost||0);return `<article data-business-key="${escapeHTML(b.id)}" class="card business-card business-card25 ${b.transport?'transport-business25':''}"><div class="business-head25"><div class="business-title25">${businessIcon24(b.type_id||b.id)}<div><h3>${escapeHTML(b.name)}${owned?` <small class="instance-label28">№ ${escapeHTML(b.instance_label||1)} · ур. ${b.level}</small>`:''}</h3><p>${escapeHTML(b.desc)}</p></div></div>${owned?`<span class="owned-badge25">${gameIcon25('check')} В портфеле</span>`:'<span class="new-badge24">Доступен</span>'}</div><div class="business-metrics25"><div><span>${owned?'Доход сейчас':'Доход после покупки'}</span><b>${fmt(owned?b.current_income:b.income_after_purchase)}/ч</b></div><div><span>Капитализация</span><b>${fmt(owned?b.capitalization:b.purchase_cost)}</b></div></div>${owned?(b.transport?renderFleet25(b):`<div class="business-upgrade-title">ТОЧКИ РОСТА</div><div class="upgrade-grid upgrade-grid25">${(b.upgrades||[]).map(u=>`<button class="upgrade-btn ${u.owned?'owned':''}" ${u.owned?'disabled':''} onclick="upgradeBusiness('${b.id}','${u.id}')"><span class="upgrade-check25">${u.owned?gameIcon25('check'):gameIcon25('up')}</span><b>${escapeHTML(u.name.replace(/^[^\p{L}\p{N}]+/u,''))}</b><small>${u.owned?'Готово':`+${u.income_bonus_percent}% дохода`}</small><strong>${u.owned?'Установлено':fmt(u.cost)}</strong></button>`).join('')}</div>`)+`<button class="sell-business" onclick="sellBusiness('${b.id}')">Продать за ${fmt(b.sell_price)}</button><div class="business-capitalization">При продаже возвращается 30% капитализации</div>`:`<button class="buy" ${canBuy?'':'disabled'} onclick="buyBusiness('${b.id}')">Купить за ${fmt(b.purchase_cost)}</button>`}</article>`;}
function restoreScroll25(y){window.scrollTo({top:y,left:0,behavior:'instant'});}
async function rerenderKeepScroll25(fn){const y=window.scrollY||document.documentElement.scrollTop||0;await fn();restoreScroll25(y);}
function quantityDialog25({title,subtitle,max,value=1}){return new Promise(resolve=>{const overlay=document.querySelector('#modal'),titleEl=document.querySelector('#modalTitle'),body=document.querySelector('#modalText'),close=document.querySelector('#modalClose');titleEl.textContent=title;body.innerHTML=`<div class="quantity-dialog25"><p>${escapeHTML(subtitle)}</p><div class="quantity-step25"><button type="button" data-q="minus">−</button><input id="quantity25" inputmode="numeric" pattern="[0-9]*" value="${Math.max(1,Math.min(max,value))}" aria-label="Количество"><button type="button" data-q="plus">+</button></div><div class="quantity-max25">Максимум: <b>${max}</b></div><div class="quantity-actions25"><button type="button" data-q="cancel">Отмена</button><button type="button" data-q="ok">Готово</button></div></div>`;overlay.classList.remove('hidden');close.style.display='none';const input=body.querySelector('#quantity25');const finish=v=>{overlay.classList.add('hidden');close.style.display='';body.onclick=null;resolve(v)};body.onclick=e=>{const a=e.target.closest('[data-q]')?.dataset.q;if(!a)return;if(a==='cancel')return finish(null);let n=Math.max(1,Math.min(max,parseInt(input.value||'1',10)||1));if(a==='minus')input.value=Math.max(1,n-1);else if(a==='plus')input.value=Math.min(max,n+1);else if(a==='ok'){if(!Number.isInteger(n)||n<1||n>max)return;finish(n)}};input.addEventListener('input',()=>{input.value=input.value.replace(/\D/g,'').slice(0,8)});setTimeout(()=>input.focus({preventScroll:true}),0);});}
let liveTimer25=null;
async function finishLiveTimer25(el){
  if(el.dataset.liveReload==='news'){
    if(page==='investments'&&investmentView==='news'&&Date.now()>=newsNextFetch25)void renderMarketNews25();
    return;
  }
  if(el.dataset.done)return;
  el.dataset.done='1';
  try{
    state=await api('/api/state');
    syncServerClock25(true);
    renderHeader();
    const reload=el.dataset.liveReload||page;
    if(reload==='businesses'&&page==='businesses')renderBusinesses();
    else if(reload==='taxes'&&page==='taxes')renderTaxes();
    else if(reload==='news'&&page==='investments'&&investmentView==='news')renderMarketNews25();
  }catch{el.dataset.done='';}
}
function tickLiveTimers25(){
  if(document.hidden)return;
  syncServerClock25();
  const nowMs=serverNow25();
  document.querySelectorAll('[data-live-until]').forEach(el=>{
    const untilMs=Number(el.dataset.liveUntil||0)*1000;
    if(!Number.isFinite(untilMs)||untilMs<=0)return;
    const left=Math.max(0,Math.ceil((untilMs-nowMs)/1000));
    const target=el.querySelector('[data-live-value]');
    if(target&&target.dataset.liveSecond!==String(left)){
      target.dataset.liveSecond=String(left);
      target.textContent=duration25(left);
    }
    if(left<=0)finishLiveTimer25(el);
  });
}
function ensureLiveTimer25(){
  if(liveTimer25!==null)return;
  tickLiveTimers25();
  // 200 ms polling keeps the displayed second aligned even after Telegram WebView
  // resumes from a short stall, while changing only a tiny text node.
  liveTimer25=setInterval(tickLiveTimers25,200);
}
ensureLiveTimer25();
document.addEventListener('visibilitychange',()=>{if(!document.hidden){syncServerClock25(true);tickLiveTimers25();}});
window.addEventListener('pageshow',()=>{syncServerClock25(true);tickLiveTimers25();});
async function buyFleetVehicle25(bid,vid){const b=state.businesses.find(x=>x.id===bid),v=b?.transport?.vehicles.find(x=>x.id===vid);if(!v)return;const max=Math.min(b.transport.available,Math.floor(Number(state.player.money)/Number(v.cost)));if(max<1){modal('Покупка','Недостаточно денег или свободных мест.');return;}const q=await quantityDialog25({title:`Купить: ${v.name}`,subtitle:`${fmt(v.cost)} за машину · свободных мест ${b.transport.available}`,max});if(q===null)return;try{const y=window.scrollY||0,r=await api(`/api/fleet/${bid}/vehicle/${vid}/buy`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:q})});state=r.state;syncServerClock25(true);renderHeader();renderBusinesses();tickLiveTimers25();restoreScroll25(y);}catch(e){modal('Не удалось купить',e.message)}}
async function sellFleetVehicle25(bid,vid){const b=state.businesses.find(x=>x.id===bid),v=b?.transport?.vehicles.find(x=>x.id===vid);if(!v?.quantity)return;const q=await quantityDialog25({title:`Продать: ${v.name}`,subtitle:`Возврат ${fmt(v.sell_price)} за машину`,max:v.quantity});if(q===null)return;try{const y=window.scrollY||0,r=await api(`/api/fleet/${bid}/vehicle/${vid}/sell`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:q})});state=r.state;syncServerClock25(true);renderHeader();renderBusinesses();tickLiveTimers25();restoreScroll25(y);}catch(e){modal('Не удалось продать',e.message)}}
async function upgradeGarage25(bid){const b=state.businesses.find(x=>x.id===bid);if(!b?.transport||b.transport.maxed||b.transport.upgrading)return;const q=await quantityDialog25({title:'Расширение автопарка',subtitle:`Расширить до ${b.transport.next_capacity} мест за ${fmt(b.transport.next_upgrade_cost)}?`,max:1});if(q===null)return;try{const y=window.scrollY||0,r=await api(`/api/fleet/${bid}/garage/upgrade`,{method:'POST'});state=r.state;syncServerClock25(true);renderHeader();renderBusinesses();tickLiveTimers25();restoreScroll25(y);}catch(e){modal('Расширение не начато',e.message)}}
window.buyFleetVehicle25=buyFleetVehicle25;window.sellFleetVehicle25=sellFleetVehicle25;window.upgradeGarage25=upgradeGarage25;window.renderBusinesses=renderBusinesses;

function removeRankDock25(){document.querySelector('#rankDock25')?.remove();}
function installRankDock25(mine){removeRankDock25();if(page!=='rating')return;const dock=document.createElement('div');dock.id='rankDock25';dock.className='rank-jump25';dock.setAttribute('aria-label','Навигация по рейтингу');dock.innerHTML=`<button type="button" onclick="jumpRating24(0)" aria-label="В начало рейтинга">${gameIcon25('up')}<span>Вверх</span></button><button type="button" onclick="jumpRating24(${mine})" ${mine<0?'disabled':''} aria-label="Моё место в рейтинге">${gameIcon25('target')}<span>Я</span></button>`;document.body.appendChild(dock);}
renderRating=async function(){const c=document.querySelector('#content');removeRankDock25();c.innerHTML='<div class="empty">Загружаем рейтинг…</div>';try{const rows=await api('/api/rating');if(page!=='rating')return;ratingRows24=rows;const mine=rows.findIndex(p=>Number(p.user_id)===Number(state.player.user_id));c.innerHTML=`<section class="rating-page"><div class="section-top"><div><div class="eyebrow">ТАБЛИЦА ЛИДЕРОВ</div><h2>Рейтинг корпораций</h2></div><span class="rank-count">${rows.length} компаний</span></div><div class="rank-summary">${mine>=0?`Твоё место <strong>#${mine+1}</strong>`:'Твоей компании пока нет в рейтинге'}<span>По полной капитализации</span></div><div class="grid">${rows.map((p,i)=>`<button id="rank-${i}" class="card rank-button ${i===mine?'rank-mine':''}" onclick="openPlayerProfile(${Number(p.user_id)})"><div class="rank-num">${String(i+1).padStart(2,'0')}</div><div><h3>${escapeHTML(p.corp_name)}${i===mine?'<small>ТЫ</small>':''}</h3><p>${fmt(p.capital)}</p><small>Свободно ${fmt(p.money)}</small></div></button>`).join('')}</div></section>`;installRankDock25(mine);requestAnimationFrame(()=>jumpRating24(mine,false));}catch(e){removeRankDock25();modal('Рейтинг',e.message)}};window.renderRating=renderRating;
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{if(btn.dataset.page!=='rating')removeRankDock25();},{capture:true}));

renderPropertyCard=function(p){const segmentNames={economy:'Эконом',business:'Бизнес',vip:'VIP'},typeNames={apartment:'Квартира',house:'Дом'},vip=p.segment==='vip';return `<article class="card property-card property-card25 ${vip?'property-vip25':''}"><div class="property-image-wrap"><img src="${p.photo}" alt="${escapeHTML(p.name)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src=propertyFallbackImage({})"><div class="property-image-shade25"></div><div class="property-badges"><span class="segment-${p.segment||'economy'}">${segmentNames[p.segment]||'Эконом'}</span><span>${typeNames[p.property_type]||''}</span>${p.prestige?`<span>${p.prestige}</span>`:''}</div></div><div class="property-body"><div class="business-head"><div><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.description)}</p></div>${p.owned?`<b class="owned-badge25">${gameIcon25('check')} Куплено</b>`:''}</div>${p.benefits?`<div class="property-benefits25">${p.benefits.map(x=>`<span>${gameIcon25('spark')}${escapeHTML(x)}</span>`).join('')}</div>`:''}<div class="property-metrics"><div><span>${p.owned?'Рыночная стоимость':'Цена'}</span><b>${fmt(p.current_value)}</b></div><div><span>Аренда</span><b>${fmt(p.rent_hour)}/ч</b></div></div><div class="property-yield">Доходность: <b>${Number(p.hourly_yield_percent||0).toFixed(2)}% / ч</b></div>${p.owned?`<div class="property-growth">${gameIcon25('chart')} Капитализация: <b>${fmt(p.capitalization)}</b></div><div class="upgrade-grid upgrade-grid25">${p.upgrades.map(u=>`<button class="upgrade-btn ${u.owned?'owned':''}" ${u.owned?'disabled':''} onclick="upgradeProperty('${p.id}','${u.id}')"><span class="upgrade-check25">${u.owned?gameIcon25('check'):gameIcon25('up')}</span><b>${escapeHTML(u.name)}</b><small>${u.owned?'Готово':`+${u.income_bonus_percent}% аренды`}</small><strong>${u.owned?'Установлено':fmt(u.cost)}</strong></button>`).join('')}</div><button class="v20-property-sell" onclick="sellProperty('${p.id}')">Продать за ${fmt(p.sell_price)}</button>`:`<button class="buy" onclick="buyProperty('${p.id}')">Купить за ${fmt(p.purchase_price)}</button>`}</div></article>`};window.renderPropertyCard=renderPropertyCard;

renderStatistics=async function(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем статистику…</div>';try{const s=await api('/api/statistics');if(page!=='statistics')return;const breakdown=(s.income_breakdown||[]);c.innerHTML=`<section class="stats-page"><article class="stats-card">${gameIcon25('money')}<span>Общая прибыль</span><b>${fmt(s.total_earned)}</b></article><article class="stats-card">${gameIcon25('chart')}<span>Общие расходы</span><b>${fmt(s.total_spent)}</b></article><article class="stats-card">${gameIcon25('building')}<span>Куплено бизнесов</span><b>${s.companies_bought}</b></article><article class="stats-card">${gameIcon25('home')}<span>Куплено недвижимости</span><b>${s.properties_bought}</b></article>${breakdown.length?`<section class="chart-card income-breakdown25"><h2>${gameIcon25('money')} Источники прибыли</h2><div class="income-breakdown-list25">${breakdown.map(x=>`<div><span>${escapeHTML(x.name)}</span><b>${fmt(x.amount)}</b></div>`).join('')}</div></section>`:''}<section class="chart-card"><h2>${gameIcon25('chart')} Прибыль по дням</h2>${renderProfitChart(s.daily_profit||[])}</section></section>`}catch(e){modal('Ошибка',e.message)}};window.renderStatistics=renderStatistics;

let newsBusy25=false,newsNextFetch25=0;
const renderMarketNews25=async()=>{
if(page!=='investments'||investmentView!=='news'||newsBusy25)return;
newsBusy25=true;
const c=document.querySelector('#content');
if(!c.querySelector('.v21-news-page'))c.innerHTML='<div class="empty">Загружаем новости рынка…</div>';
try{const d=await api('/api/market-news');if(page!=='investments'||investmentView!=='news')return;const cards=(d.news||[]).map((n,index)=>{const cls=n.sentiment==='good'?'v21-good':'v21-bad',label=n.sentiment==='good'?'ПОЗИТИВНЫЙ СИГНАЛ':'НЕГАТИВНЫЙ СИГНАЛ',reaction=n.applied?`<div class="v21-news-reaction ${cls}"><b>Изменение: ${Number(n.impact_percent)>=0?'+':''}${Number(n.impact_percent).toFixed(2)}%</b> · ${fmt(n.price_before)} → ${fmt(n.price_after)}</div>`:`<div class="v21-news-reaction ${cls}" data-live-until="${Number(n.impact_at||0)}" data-live-reload="news"><b>${label}</b> · <span>Переоценка рынка через <b data-live-value>${duration25(n.seconds_to_impact??0)}</b></span></div>`;const fullPhoto=`/static/news/${encodeURIComponent(n.stock_id)}.webp?v=263`,smallPhoto=`/static/news/${encodeURIComponent(n.stock_id)}.sm.webp?v=263`;return `<article class="v21-news-card" data-business-key="news-${Number(n.id)}"><div class="news-photo-frame25"><img class="v21-news-photo" src="${fullPhoto}" srcset="${smallPhoto} 960w, ${fullPhoto} 1600w" sizes="(max-width: 760px) 100vw, 760px" width="1600" height="900" alt="${escapeHTML(n.company)}" loading="${index===0?'eager':'lazy'}" fetchpriority="${index===0?'high':'low'}" decoding="async"></div><div class="v21-news-body"><div class="v21-news-kicker"><span>CORPORATION JOURNAL · ${escapeHTML(n.symbol)}</span><span>${v21Date(n.published_at)}</span></div><h3>${escapeHTML(n.title)}</h3><p>${escapeHTML(n.article)}</p>${reaction}</div></article>`}).join('');const html=`<section class="v21-news-page"><div class="v21-news-head"><div><div class="eyebrow">MARKET NEWS</div><h2>${gameIcon25('news')} Новости рынка</h2></div><button class="back-button" onclick="v21BackInvestments()">← Назад</button></div>${cards||'<div class="empty">Новостей пока нет.</div>'}</section>`;
const current=c.querySelector('.v21-news-page'),template=document.createElement('template');template.innerHTML=html;
if(current&&typeof patchNode28==='function')patchNode28(current,template.content.firstElementChild);
else c.innerHTML=html;
newsNextFetch25=Date.now()+5000;
tickLiveTimers25();
}catch(e){
if(page==='investments'&&investmentView==='news'&&!c.querySelector('.v21-news-page'))c.innerHTML='<div class="empty">Не удалось загрузить новости. <button onclick="renderMarketNews()">Повторить</button></div>';
}finally{newsNextFetch25=Date.now()+5000;newsBusy25=false;}
};
setInterval(()=>{if(!document.hidden&&page==='investments'&&investmentView==='news'&&Date.now()>=newsNextFetch25)void renderMarketNews25();},15000);
renderMarketNews=renderMarketNews25;window.renderMarketNews=renderMarketNews25;

const investmentBase25=renderInvestments;renderInvestments=async function(){await investmentBase25();document.querySelectorAll('.v21-news-entry').forEach(b=>b.innerHTML=`${gameIcon25('news')}<span>Новости рынка</span><i>›</i>`);};window.renderInvestments=renderInvestments;

capGrid=function(b){return `<div class="v20-capital-grid"><article class="stats-card">${gameIcon25('money')}<span>Свободные деньги</span><b>${fmt(b.cash)}</b></article><article class="stats-card">${gameIcon25('building')}<span>Бизнесы</span><b>${fmt(b.businesses)}</b></article><article class="stats-card">${gameIcon25('chart')}<span>Акции</span><b>${fmt(b.stocks)}</b></article><article class="stats-card">${gameIcon25('money')}<span>Облигации</span><b>${fmt(b.bonds)}</b></article><article class="stats-card">${gameIcon25('home')}<span>Недвижимость</span><b>${fmt(b.real_estate)}</b></article></div>`};window.capGrid=capGrid;
openPlayerProfile=async function(id){removeRankDock25();const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем профиль…</div>';try{const p=await api(`/api/player/${id}`);if(page!=='rating')return;const businesses=p.businesses?.length?p.businesses.map(b=>`<article class="profile-business"><div><h3>${escapeHTML(b.name)}</h3><p>${escapeHTML(b.description)}</p></div><b>ур. ${b.level}</b></article>`).join(''):'<div class="empty">Бизнесов пока нет.</div>';c.innerHTML=`<section class="profile-page"><button class="back-button" onclick="backToRating()">← Назад к рейтингу</button><article class="profile-header"><div class="eyebrow">ПРОФИЛЬ ИГРОКА</div><h2>${escapeHTML(p.player.corp_name)}</h2><p>${gameIcon25('spark')} Общий капитал: ${fmt(p.capital)}</p><p>${gameIcon25('money')} Свободные деньги: ${fmt(p.player.money)}</p><p>${gameIcon25('chart')} Автодоход: ${fmt(p.hourly_income)}/ч</p></article>${capGrid(p.capital_breakdown||{})}<section class="profile-businesses"><h2>${gameIcon25('building')} Бизнесы</h2>${businesses}</section></section>`}catch(e){modal('Ошибка',e.message)}};window.openPlayerProfile=openPlayerProfile;
renderTaxes=function(){const t=state?.taxes||{},u=Number(t.unpaid||0),b=Boolean(t.blocked),until=serverNow25()/1000+Number(t.seconds_left||0);renderStableContent28(document.querySelector('#content'),`<section class="tax-page"><article class="tax-hero ${b?'tax-blocked':''}"><div class="eyebrow">НАЛОГОВАЯ СИСТЕМА</div><h2>${gameIcon25(b?'clock':'money')} ${b?'Доход остановлен':'Налоги'}</h2><p>Налог — 5% с автоматического дохода, дивидендов, дохода по облигациям, аренды и прибыли от продажи акций.</p></article><article class="stats-card"><span>Неоплаченный налог</span><b>${fmt(u)}</b></article><article class="card tax-info" ${u>0&&!b?`data-live-until="${until}" data-live-reload="taxes"`:''}>${u>0?(b?'Срок оплаты истёк. Весь пассивный доход остановлен.':`До остановки дохода: <b data-live-value>${duration25(t.seconds_left)}</b>.`):'Задолженности нет.'}</article><button class="buy" ${u>0?'':'disabled'} onclick="payTaxes()">${u>0?`Оплатить ${fmt(u)}`:'Налогов к оплате нет'}</button></section>`);tickLiveTimers25()};window.renderTaxes=renderTaxes;
const oldOpenCity25=openCity;openCity=function(id){oldOpenCity25(id);const h=document.querySelector('.realestate-page>h2');if(h){h.textContent=h.textContent.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,'').trim();h.insertAdjacentHTML('afterbegin',gameIcon25('home'));}};window.openCity=openCity;

function cleanEmojiText25(root){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes)n.nodeValue=n.nodeValue.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,'').replace(/\s{2,}/g,' ');}
cleanEmojiText25(document.body);const emojiObserver25=new MutationObserver(records=>{for(const r of records)for(const node of r.addedNodes){if(node.nodeType===Node.TEXT_NODE)node.nodeValue=node.nodeValue.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,'');else if(node.nodeType===Node.ELEMENT_NODE)cleanEmojiText25(node);}});const dynamicContent25=document.querySelector('#content');if(dynamicContent25)emojiObserver25.observe(dynamicContent25,{subtree:true,childList:true});

const STOCK_LOGOS25={bmw:'https://cdn.simpleicons.org/bmw/FFFFFF',kfc:'https://cdn.simpleicons.org/kfc/FFFFFF',spotify:'https://cdn.simpleicons.org/spotify/1ED760',nvidia:'https://cdn.simpleicons.org/nvidia/76B900',tesla:'https://cdn.simpleicons.org/tesla/E82127',mcdonalds:'https://cdn.simpleicons.org/mcdonalds/FFC72C',toyota:'https://cdn.simpleicons.org/toyota/EB0A1E',apple:'https://cdn.simpleicons.org/apple/FFFFFF',google:'https://cdn.simpleicons.org/google/FFFFFF',intel:'https://cdn.simpleicons.org/intel/0071C5'};
function stockLogo25(id,name){const src=STOCK_LOGOS25[String(id)],fallback=escapeHTML(String(name||id||'?').slice(0,2).toUpperCase());return src?`<img class="stock-logo-img25" src="${src}" alt="${escapeHTML(name||id)}" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="stock-logo-fallback25" hidden>${fallback}</span>`:`<span>${fallback}</span>`}
renderStockCard=function(stock){const change=Number(stock.change_percent||0),owned=Number(getHolding(stock.id)?.quantity||0);return `<button class="corp-stock-row" type="button" onclick="openStock('${stock.id}')"><div class="corp-stock-icon corp-stock-icon25">${stockLogo25(stock.id,stock.name)}</div><div class="corp-stock-name"><strong>${escapeHTML(stock.name)}</strong><span>${owned>0?`В портфеле · ${owned} шт.`:'Доступно'}</span></div><div class="corp-stock-quote"><strong>${fmt(stock.current_price)}</strong><span class="${change>=0?'positive':'negative'}">${change>=0?'+':'−'} ${Math.abs(change).toFixed(2)}%</span><small class="quote-period">к предыдущей котировке</small></div><span class="corp-stock-arrow">›</span></button>`};window.renderStockCard=renderStockCard;
const openStockBase25=openStock;openStock=async function(id,keepScroll=false){await openStockBase25(id,keepScroll);const box=document.querySelector('.corp-stock-logo-large');if(box){const s=stocksCache.find(x=>String(x.id)===String(id));box.classList.add('corp-stock-icon25');box.innerHTML=stockLogo25(id,s?.name||id)}};window.openStock=openStock;
openTrade=async function(id,side){const s=stocksCache.find(x=>String(x.id)===String(id));if(!s)return;const h=getHolding(id),owned=Number(h?.quantity||0),price=Number(s.current_price||0),max=side==='buy'?Math.floor(Number(state.player.money||0)/price):owned;if(max<=0){modal('Сделка',side==='buy'?'Недостаточно средств для покупки.':'У тебя нет этих акций.');return}const qty=await quantityDialog25({title:`${side==='buy'?'Покупка':'Продажа'} ${s.name}`,subtitle:`Цена ${fmt(price)}`,max});if(qty===null)return;try{const y=window.scrollY||0,r=await api(`/api/stocks/${id}/${side}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:qty})});state=r.state;renderHeader();await Promise.all([loadStocks(),loadBrokerage()]);if(corporationActiveStockId===String(id))await openStock(id,true);else await renderInvestments();restoreScroll25(y);modal(side==='buy'?'Акции куплены':'Акции проданы',side==='sell'&&Number(r.realized_profit)>0?`Прибыль сделки: ${fmt(r.realized_profit)}\nНалог с прибыли: ${fmt(r.profit_tax)}`:`Сумма сделки: ${fmt(side==='buy'?r.total_cost:r.total_income)}`)}catch(e){modal('Сделка не выполнена',e.message)}};window.openTrade=openTrade;
const baseRenderTaxes25=renderTaxes;renderTaxes=function(){syncServerClock25();baseRenderTaxes25()};window.renderTaxes=renderTaxes;

