(() => {
const css=`
.v20-capital-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.v20-capital-grid .stats-card{margin:0}.v20-action-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.v20-action-grid button{min-height:44px;border-radius:13px}.v20-secondary{background:rgba(255,255,255,.05);color:var(--text);border:1px solid var(--line)}.v20-sell-all{background:rgba(255,90,82,.08);color:#ff7b75;border:1px solid rgba(255,90,82,.3)}.v20-property-sell{width:100%;margin-top:10px;min-height:46px;border-radius:14px;background:rgba(255,90,82,.08);color:#ff7b75;border:1px solid rgba(255,90,82,.3)}.v20-cap-note{font-size:11px;color:var(--hint);margin-top:8px}.v21-news-entry{width:100%;min-height:52px;margin:0 0 12px;padding:13px 15px;border:1px solid rgba(230,194,84,.28);border-radius:16px;background:linear-gradient(145deg,rgba(230,194,84,.12),rgba(255,255,255,.025));color:var(--text);font-size:15px;font-weight:850;text-align:left}.v21-news-page{display:grid;gap:14px}.v21-news-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.v21-news-head h2{margin:0}.v21-news-next{font-size:11px;color:var(--hint)}.v21-news-card{overflow:hidden;border:1px solid var(--line);border-radius:20px;background:var(--card)}.v21-news-photo{width:100%;height:180px;object-fit:cover;display:block}.v21-news-body{padding:15px}.v21-news-kicker{display:flex;justify-content:space-between;gap:8px;color:var(--hint);font-size:10px;font-weight:900;letter-spacing:.7px;text-transform:uppercase}.v21-news-body h3{margin:9px 0 9px;font-size:20px;line-height:1.2}.v21-news-body p{margin:0;color:var(--text);font-size:13px;line-height:1.55}.v21-news-reaction{margin-top:13px;padding-top:12px;border-top:1px solid var(--line);font-size:12px}.v21-good{color:var(--positive)}.v21-bad{color:var(--negative)}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);

function capGrid(b){return `<div class="v20-capital-grid"><article class="stats-card"><span>💵 Свободные деньги</span><b>${fmt(b.cash)}</b></article><article class="stats-card"><span>🏢 Бизнесы</span><b>${fmt(b.businesses)}</b></article><article class="stats-card"><span>📈 Акции</span><b>${fmt(b.stocks)}</b></article><article class="stats-card"><span>🏦 Облигации</span><b>${fmt(b.bonds)}</b></article><article class="stats-card"><span>🏠 Недвижимость</span><b>${fmt(b.real_estate)}</b></article></div>`}

renderStatistics=async function(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем статистику...</div>';try{const s=await api('/api/statistics');c.innerHTML=`<section class="stats-page"><article class="stats-card"><span>👑 Общий капитал</span><b>${fmt(s.capital)}</b><div class="v20-cap-note">Рейтинг учитывает деньги + 100% капитализации бизнесов + текущую стоимость акций и облигаций + полную капитализацию недвижимости.</div></article>${capGrid(s.capital_breakdown||{})}<article class="stats-card"><span>💰 Общая полученная прибыль</span><b>${fmt(s.total_earned)}</b></article><article class="stats-card"><span>💸 Общие расходы</span><b>${fmt(s.total_spent)}</b></article><article class="stats-card"><span>🏢 Куплено бизнесов</span><b>${s.companies_bought}</b></article><article class="stats-card"><span>🏠 Куплено недвижимости</span><b>${s.properties_bought}</b></article><section class="chart-card"><h2>📊 Прибыль по дням</h2>${renderProfitChart(s.daily_profit||[])}</section></section>`}catch(e){modal('Ошибка',e.message)}};

renderRating=async function(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем рейтинг...</div>';try{const rows=await api('/api/rating');c.innerHTML=`<div class="grid">${rows.map((p,i)=>`<button class="card rank-button" onclick="openPlayerProfile(${p.user_id})"><div class="rank-num">#${i+1}</div><div><h3>${escapeHTML(p.corp_name)}</h3><p>👑 Капитал: ${fmt(p.capital)}</p><small>Свободно: ${fmt(p.money)}</small></div></button>`).join('')}</div>`}catch(e){modal('Ошибка',e.message)}};

openPlayerProfile=async function(id){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем профиль...</div>';try{const p=await api(`/api/player/${id}`);const businesses=p.businesses?.length?p.businesses.map(b=>`<article class="profile-business"><div><h3>${b.name}</h3><p>${b.description}</p></div><b>ур. ${b.level}</b></article>`).join(''):'<div class="empty">Бизнесов пока нет.</div>';c.innerHTML=`<section class="profile-page"><button class="back-button" onclick="backToRating()">← Назад к рейтингу</button><article class="profile-header"><div class="eyebrow">ПРОФИЛЬ ИГРОКА</div><h2>${escapeHTML(p.player.corp_name)}</h2><p>👑 Общий капитал: ${fmt(p.capital)}</p><p>💵 Свободные деньги: ${fmt(p.player.money)}</p><p>📈 Автодоход: ${fmt(p.hourly_income)}/ч</p></article>${capGrid(p.capital_breakdown||{})}<section class="profile-businesses"><h2>🏢 Бизнесы</h2>${businesses}</section></section>`}catch(e){modal('Ошибка',e.message)}};

async function tradeAllStock(id,side){const s=stocksCache.find(x=>String(x.id)===String(id));if(!s)return;const h=getHolding(id),owned=Number(h?.quantity||0),price=Number(s.current_price||0);const qty=side==='buy'?Math.floor(Number(state.player.money||0)/price):owned;if(qty<=0){modal('Сделка',side==='buy'?'Недостаточно денег.':'У тебя нет этих акций.');return}if(!confirm(`${side==='buy'?'Купить на все свободные деньги':'Продать все'}: ${qty} шт. ${s.name}?`))return;try{const r=await api(`/api/stocks/${id}/${side}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:qty})});state=r.state;renderHeader();await Promise.all([loadStocks(),loadBrokerage()]);await openStock(id,true);modal('Готово',`Количество: ${qty} шт.\nСумма: ${fmt(side==='buy'?r.total_cost:r.total_income)}`)}catch(e){modal('Сделка не выполнена',e.message)}}
window.tradeAllStock=tradeAllStock;

openStock=async function(id,keepScroll=false){const c=document.querySelector('#content');if(!keepScroll)corporationStockReturnScroll=window.scrollY||0;corporationActiveStockId=String(id);investmentView='stocks';const savedScroll=window.scrollY;if(!keepScroll)c.innerHTML='<div class="empty">Загружаем акцию...</div>';try{const s=await api(`/api/stocks/${id}`),h=getHolding(id),owned=Number(h?.quantity||0),change=Number(s.change_percent||0);if(page!=='investments'||corporationActiveStockId!==String(id))return;stocksCache=stocksCache.map(x=>String(x.id)===String(s.id)?{...x,...s}:x);const canAll=Math.floor(Number(state.player.money||0)/Number(s.current_price||1));renderStableContent28(c,`<section class="corp-stock-page"><div class="corp-stock-page-top"><button class="corp-stock-back" onclick="corporationCloseStock()">←</button></div><div class="corp-stock-company"><div class="corp-stock-logo-large">${String(s.symbol||s.name||'?').slice(0,2).toUpperCase()}</div><div class="corp-stock-symbol">${s.symbol||''}</div><h2>${s.name}</h2></div><article class="corp-stock-chart-card"><div class="corp-stock-chart-head"><div><span>Текущая цена</span><strong>${fmt(s.current_price)}</strong><small class="${change>=0?'positive':'negative'}">${change>=0?'+':'−'} ${Math.abs(change).toFixed(2)}%</small><small class="quote-period">к предыдущей котировке</small></div><button class="corp-chart-switch" onclick="corporationToggleStockChart('${s.id}')">${corporationStockViewMode==='candles'?'〽 Линия':'🕯 Свечи'}</button></div>${corporationRenderChart(s.history||[],corporationStockViewMode)}<div class="corp-extreme-note">Свеча — 5 минут: открытие, максимум, минимум, закрытие по игровым котировкам. MAX/MIN — экстремумы видимой истории.</div></article><div class="v20-action-grid"><button class="corp-stock-buy-main" onclick="openTrade('${s.id}','buy')">Купить</button><button data-buy-stock="${s.id}" class="v20-secondary" ${canAll>0?'':'disabled'} onclick="tradeAllStock('${s.id}','buy')">Купить на все · ${canAll} шт.</button>${owned>0?`<button class="corp-stock-sell-main" onclick="openTrade('${s.id}','sell')">Продать</button><button class="v20-sell-all" onclick="tradeAllStock('${s.id}','sell')">Продать все · ${owned} шт.</button>`:''}</div><section class="corp-stock-info"><h2>Сведения</h2><div class="corp-stock-info-row"><span>Стоимость одной акции</span><strong>${fmt(s.current_price)}</strong></div><div class="corp-stock-info-row"><span>В портфеле</span><strong>${owned} шт.</strong></div><div class="corp-stock-info-row"><span>Дивиденды</span><strong>${Number(s.dividend_rate_percent||0).toFixed(2)}% / ч</strong></div><div class="corp-stock-description"><span>О компании</span><p>${s.description||'Описание компании пока отсутствует.'}</p></div></section></section>`);window.scrollTo({top:keepScroll?savedScroll:0,left:0,behavior:'instant'})}catch(e){corporationActiveStockId=null;modal('Ошибка',e.message);await renderInvestments()}};
window.openStock=openStock;

renderBondCard=function(b){const owned=Number(b.quantity||0),max=Math.floor(Number(state?.player?.money||0)/Number(b.price||1));return `<article class="card bond-card"><div class="business-head"><div><div class="stock-symbol">${b.symbol}</div><h3>${b.name}</h3><p>${b.description}</p></div><b>${fmt(b.price)}</b></div><div class="bond-yield">💰 Доходность: <b>${b.yield_rate_percent}% в час</b></div><div class="holding-row"><span>У тебя</span><b>${owned} шт.</b></div><div class="holding-row"><span>Доход</span><b>${fmt(b.income_hour)}/ч</b></div><div class="v20-action-grid"><button class="buy" onclick="openBondTrade('${b.id}','buy')">Купить</button><button data-buy-bond="${b.id}" class="v20-secondary" ${max>0?'':'disabled'} onclick="tradeAllBond('${b.id}','buy')">Купить на все · ${max}</button><button class="stock-sell" ${owned>0?'':'disabled'} onclick="openBondTrade('${b.id}','sell')">Продать</button><button class="v20-sell-all" ${owned>0?'':'disabled'} onclick="tradeAllBond('${b.id}','sell')">Продать все · ${owned}</button></div></article>`};
async function tradeAllBond(id,side){const b=bondsCache.find(x=>String(x.id)===String(id));if(!b)return;const qty=side==='buy'?Math.floor(Number(state.player.money||0)/Number(b.price||1)):Number(b.quantity||0);if(qty<=0){modal('Облигации',side==='buy'?'Недостаточно денег.':'У тебя нет этих облигаций.');return}if(!confirm(`${side==='buy'?'Купить на все свободные деньги':'Продать все'}: ${qty} шт. ${b.symbol}?`))return;try{const r=await api(`/api/bonds/${id}/${side}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:qty})});state=r.state;bondsCache=r.bonds||await loadBonds();renderHeader();await renderInvestments();modal('Готово',`Количество: ${qty} шт.\nСумма: ${fmt(side==='buy'?r.total_cost:r.total_income)}`)}catch(e){modal('Операция не выполнена',e.message)}}
window.tradeAllBond=tradeAllBond;

renderRealEstate=async function(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем карту...</div>';try{const d=await api('/api/real-estate');realEstateCache=d.properties||[];const yields=realEstateCache.map(x=>Number(x.hourly_yield_percent||0)).filter(x=>x>0);const minY=yields.length?Math.min(...yields):0,maxY=yields.length?Math.max(...yields):0;c.innerHTML=`<section class="realestate-page"><div><div class="eyebrow">МИРОВАЯ НЕДВИЖИМОСТЬ</div><h2>🌍 Карта мира</h2><p class="section-note">Приближай карту и нажимай на маркеры городов.</p></div><div id="worldMap" class="world-map"></div><div class="realestate-summary"><span>🏠 Куплено объектов</span><b>${state.real_estate_count||0}</b><span>💰 Базовая доходность</span><b>${minY.toFixed(2)}–${maxY.toFixed(2)}% / ч</b></div></section>`;setTimeout(initWorldMap,0)}catch(e){modal('Недвижимость',e.message)}};

renderPropertyCard=function(p){const segmentNames={economy:'Эконом',business:'Бизнес',vip:'VIP'},typeNames={apartment:'Квартира',house:'Дом'};return `<article class="card property-card"><div class="property-image-wrap"><img src="${p.photo}" alt="${p.name}" loading="lazy" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src=propertyFallbackImage({})"><div class="property-badges"><span class="segment-${p.segment||'economy'}">${segmentNames[p.segment]||'Эконом'}</span><span>${typeNames[p.property_type]||''}</span></div></div><div class="property-body"><div class="business-head"><div><h3>${p.name}</h3><p>${p.description}</p></div>${p.owned?'<b>✅ Куплено</b>':''}</div><div class="property-metrics"><div><span>${p.owned?'Рыночная стоимость':'Цена'}</span><b>${fmt(p.current_value)}</b></div><div><span>Аренда</span><b>${fmt(p.rent_hour)}/ч</b></div></div><div class="property-yield">Доходность аренды: <b>${Number(p.hourly_yield_percent||0).toFixed(2)}% / ч</b></div>${p.owned?`<div class="property-growth">📈 Полная капитализация с улучшениями: <b>${fmt(p.capitalization)}</b></div><div class="upgrade-grid">${p.upgrades.map(u=>`<button class="upgrade-btn ${u.owned?'owned':''}" ${u.owned?'disabled':''} onclick="upgradeProperty('${p.id}','${u.id}')"><b>${u.name}</b><span>${u.owned?'Установлено':`+${u.income_bonus_percent}% к аренде · ${fmt(u.cost)}`}</span></button>`).join('')}</div><button class="v20-property-sell" onclick="sellProperty('${p.id}')">Продать за 100% капитализации · ${fmt(p.sell_price)}</button>`:`<button class="buy" onclick="buyProperty('${p.id}')">Купить за ${fmt(p.purchase_price)}</button>`}</div></article>`};
async function sellProperty(id){const p=realEstateCache.find(x=>String(x.id)===String(id));if(!p||!p.owned)return;if(!confirm(`Продать ${p.name} за ${fmt(p.sell_price)}?`))return;try{const r=await api(`/api/real-estate/${id}/sell`,{method:'POST'});state=r.state;realEstateCache=r.properties;renderHeader();const next=realEstateCache.find(x=>x.id===id);openCity(next.city_id);modal('Недвижимость продана',`Получено ${fmt(r.sell_price)}.`)}catch(e){modal('Продажа не выполнена',e.message)}}
window.sellProperty=sellProperty;
window.renderStatistics=renderStatistics;window.renderRating=renderRating;window.openPlayerProfile=openPlayerProfile;window.renderRealEstate=renderRealEstate;window.renderPropertyCard=renderPropertyCard;window.renderBondCard=renderBondCard;
})();

// === CORPORATION V21: MARKET NEWS ==========================================
let v21NewsTimer=null;
function v21Date(ts){return ts?new Date(Number(ts)*1000).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}
function v21Countdown(sec){sec=Math.max(0,Number(sec||0));const m=Math.floor(sec/60),s=Math.floor(sec%60);return `${m}:${String(s).padStart(2,'0')}`}
async function renderMarketNews(){
  const c=document.querySelector('#content');
  if(!c.querySelector('.v21-news-page'))c.innerHTML='<div class="empty">Загружаем новости рынка...</div>';
  try{
    const d=await api('/api/market-news');
    if(page!=='investments'||investmentView!=='news')return;
    const clockOffset=Number(d.server_time)*1000-Date.now();
    const now=Number(d.server_time||Math.floor(Date.now()/1000));
    const next=Math.max(0,Number(d.next_news_at||0)-now);
    const cards=(d.news||[]).map(n=>{
      const cls=n.sentiment==='good'?'v21-good':'v21-bad';
      const label=n.sentiment==='good'?'ПОЗИТИВНЫЙ СИГНАЛ':'НЕГАТИВНЫЙ СИГНАЛ';
      const reaction=n.applied
        ? `<div class="v21-news-reaction ${cls}"><b>Рынок отреагировал: ${Number(n.impact_percent)>=0?'+':''}${Number(n.impact_percent).toFixed(2)}%</b> · ${fmt(n.price_before)} → ${fmt(n.price_after)}</div>`
        : `<div class="v21-news-reaction ${cls}"><b>${label}</b> · переоценка рынка через <span data-impact-at="${n.impact_at}">${v21Countdown(n.seconds_to_impact)}</span></div>`;
      return `<article class="v21-news-card"><img class="v21-news-photo" src="${n.photo}" alt="${n.company}" loading="lazy"><div class="v21-news-body"><div class="v21-news-kicker"><span>CORPORATION JOURNAL · ${n.symbol}</span><span>${v21Date(n.published_at)}</span></div><h3>${n.title}</h3><p>${n.article}</p>${reaction}</div></article>`;
    }).join('');
    c.innerHTML=`<section class="v21-news-page"><div class="v21-news-head"><div><div class="eyebrow">MARKET NEWS</div><h2>📰 Новости рынка</h2></div><button class="back-button" onclick="v21BackInvestments()">← Назад</button></div><div class="v21-news-next">Вымышленные события игрового рынка. Публикации появляются нерегулярно; реакция котировок — через 2 минуты.</div>${cards||'<div class="empty">Новостей пока нет.</div>'}</section>`;
    clearInterval(v21NewsTimer);
    let refreshPending=false;
    const tick=()=>{
      if(page!=='investments'||investmentView!=='news'){clearInterval(v21NewsTimer);return;}
      const now=Math.floor((Date.now()+clockOffset)/1000);
      let due=false;
      document.querySelectorAll('[data-impact-at],[data-news-at]').forEach(el=>{
        const at=Number(el.dataset.impactAt||el.dataset.newsAt);
        const left=Math.max(0,at-now);
        el.textContent=left===0?'ожидаем обновление':v21Countdown(left);
        if(at>0&&left===0)due=true;
      });
      if((due||now-Number(d.server_time)>=30)&&!refreshPending){
        refreshPending=true;
        setTimeout(()=>{if(page==='investments'&&investmentView==='news')renderMarketNews();},2000);
      }
    };
    tick();v21NewsTimer=setInterval(tick,1000);
  }catch(e){modal('Ошибка',e.message)}
}
function openInvestmentNews(){corporationActiveStockId=null;investmentView='news';return renderMarketNews()}
function v21BackInvestments(){investmentView='home';clearInterval(v21NewsTimer);return renderInvestments()}
window.openInvestmentNews=openInvestmentNews;window.renderMarketNews=renderMarketNews;window.v21BackInvestments=v21BackInvestments;

const v21BaseRenderInvestments=renderInvestments;
renderInvestments=async function(){
  if(corporationActiveStockId){await Promise.all([loadStocks(),loadBrokerage()]);if(page==='investments'&&corporationActiveStockId)return openStock(corporationActiveStockId,true);return;}
  if(investmentView==='news')return renderMarketNews();
  clearInterval(v21NewsTimer);
  await v21BaseRenderInvestments();
  const c=document.querySelector('#content');
  if(page!=='investments'||!c||c.querySelector('.v21-news-entry')||corporationActiveStockId)return;
  const container=c.querySelector('.investment-page')||c.firstElementChild;
  if(container){const b=document.createElement('button');b.type='button';b.className='v21-news-entry';b.innerHTML='📰 Новости рынка <span style="float:right">›</span>';b.onclick=openInvestmentNews;container.insertBefore(b,container.children[1]||container.firstChild)}
};
window.renderInvestments=renderInvestments;
// ============================================================================

