(() => {
const css=`
.v20-capital-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.v20-capital-grid .stats-card{margin:0}.v20-action-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.v20-action-grid button{min-height:44px;border-radius:13px}.v20-secondary{background:rgba(255,255,255,.05);color:var(--text);border:1px solid var(--line)}.v20-sell-all{background:rgba(255,90,82,.08);color:#ff7b75;border:1px solid rgba(255,90,82,.3)}.v20-property-sell{width:100%;margin-top:10px;min-height:46px;border-radius:14px;background:rgba(255,90,82,.08);color:#ff7b75;border:1px solid rgba(255,90,82,.3)}.v20-cap-note{font-size:11px;color:var(--hint);margin-top:8px}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);

function capGrid(b){return `<div class="v20-capital-grid"><article class="stats-card"><span>💵 Свободные деньги</span><b>${fmt(b.cash)}</b></article><article class="stats-card"><span>🏢 Бизнесы</span><b>${fmt(b.businesses)}</b></article><article class="stats-card"><span>📈 Акции</span><b>${fmt(b.stocks)}</b></article><article class="stats-card"><span>🏦 Облигации</span><b>${fmt(b.bonds)}</b></article><article class="stats-card"><span>🏠 Недвижимость</span><b>${fmt(b.real_estate)}</b></article></div>`}

renderStatistics=async function(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем статистику...</div>';try{const s=await api('/api/statistics');c.innerHTML=`<section class="stats-page"><article class="stats-card"><span>👑 Общий капитал</span><b>${fmt(s.capital)}</b><div class="v20-cap-note">Рейтинг учитывает деньги + 100% капитализации бизнесов + текущую стоимость акций и облигаций + полную капитализацию недвижимости.</div></article>${capGrid(s.capital_breakdown||{})}<article class="stats-card"><span>💰 Общая полученная прибыль</span><b>${fmt(s.total_earned)}</b></article><article class="stats-card"><span>💸 Общие расходы</span><b>${fmt(s.total_spent)}</b></article><article class="stats-card"><span>🏢 Куплено бизнесов</span><b>${s.companies_bought}</b></article><article class="stats-card"><span>🏠 Куплено недвижимости</span><b>${s.properties_bought}</b></article><section class="chart-card"><h2>📊 Прибыль по дням</h2>${renderProfitChart(s.daily_profit||[])}</section></section>`}catch(e){modal('Ошибка',e.message)}};

renderRating=async function(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем рейтинг...</div>';try{const rows=await api('/api/rating');c.innerHTML=`<div class="grid">${rows.map((p,i)=>`<button class="card rank-button" onclick="openPlayerProfile(${p.user_id})"><div class="rank-num">#${i+1}</div><div><h3>${p.corp_name}</h3><p>👑 Капитал: ${fmt(p.capital)}</p><small>Свободно: ${fmt(p.money)}</small></div></button>`).join('')}</div>`}catch(e){modal('Ошибка',e.message)}};

openPlayerProfile=async function(id){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем профиль...</div>';try{const p=await api(`/api/player/${id}`);const businesses=p.businesses?.length?p.businesses.map(b=>`<article class="profile-business"><div><h3>${b.name}</h3><p>${b.description}</p></div><b>ур. ${b.level}</b></article>`).join(''):'<div class="empty">Бизнесов пока нет.</div>';c.innerHTML=`<section class="profile-page"><button class="back-button" onclick="backToRating()">← Назад к рейтингу</button><article class="profile-header"><div class="eyebrow">ПРОФИЛЬ ИГРОКА</div><h2>${p.player.corp_name}</h2><p>👑 Общий капитал: ${fmt(p.capital)}</p><p>💵 Свободные деньги: ${fmt(p.player.money)}</p><p>📈 Автодоход: ${fmt(p.hourly_income)}/ч</p></article>${capGrid(p.capital_breakdown||{})}<section class="profile-businesses"><h2>🏢 Бизнесы</h2>${businesses}</section></section>`}catch(e){modal('Ошибка',e.message)}};

async function tradeAllStock(id,side){const s=stocksCache.find(x=>String(x.id)===String(id));if(!s)return;const h=getHolding(id),owned=Number(h?.quantity||0),price=Number(s.current_price||0);const qty=side==='buy'?Math.floor(Number(state.player.money||0)/price):owned;if(qty<=0){modal('Сделка',side==='buy'?'Недостаточно денег.':'У тебя нет этих акций.');return}if(!confirm(`${side==='buy'?'Купить на все свободные деньги':'Продать все'}: ${qty} шт. ${s.name}?`))return;try{const r=await api(`/api/stocks/${id}/${side}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:qty})});state=r.state;renderHeader();await Promise.all([loadStocks(),loadBrokerage()]);await openStock(id,true);modal('Готово',`Количество: ${qty} шт.\nСумма: ${fmt(side==='buy'?r.total_cost:r.total_income)}`)}catch(e){modal('Сделка не выполнена',e.message)}}
window.tradeAllStock=tradeAllStock;

openStock=async function(id,keepScroll=false){const c=document.querySelector('#content');if(!keepScroll)corporationStockReturnScroll=window.scrollY||0;corporationActiveStockId=String(id);investmentView='stocks';c.innerHTML='<div class="empty">Загружаем акцию...</div>';try{const s=await api(`/api/stocks/${id}`),h=getHolding(id),owned=Number(h?.quantity||0),change=Number(s.change_percent||0);stocksCache=stocksCache.map(x=>String(x.id)===String(s.id)?{...x,...s}:x);const canAll=Math.floor(Number(state.player.money||0)/Number(s.current_price||1));c.innerHTML=`<section class="corp-stock-page"><div class="corp-stock-page-top"><button class="corp-stock-back" onclick="corporationCloseStock()">←</button></div><div class="corp-stock-company"><div class="corp-stock-logo-large">${String(s.symbol||s.name||'?').slice(0,2).toUpperCase()}</div><div class="corp-stock-symbol">${s.symbol||''}</div><h2>${s.name}</h2></div><article class="corp-stock-chart-card"><div class="corp-stock-chart-head"><div><span>Текущая цена</span><strong>${fmt(s.current_price)}</strong><small class="${change>=0?'positive':'negative'}">${change>=0?'+':'−'} ${Math.abs(change).toFixed(2)}%</small></div><button class="corp-chart-switch" onclick="corporationToggleStockChart('${s.id}')">${corporationStockViewMode==='candles'?'〽 Линия':'🕯 Свечи'}</button></div>${corporationRenderChart(s.history||[],corporationStockViewMode)}<div class="corp-extreme-note">MAX и MIN — максимум и минимум видимой истории графика.</div></article><div class="v20-action-grid"><button class="corp-stock-buy-main" onclick="openTrade('${s.id}','buy')">Купить</button><button class="v20-secondary" ${canAll>0?'':'disabled'} onclick="tradeAllStock('${s.id}','buy')">Купить на все · ${canAll} шт.</button>${owned>0?`<button class="corp-stock-sell-main" onclick="openTrade('${s.id}','sell')">Продать</button><button class="v20-sell-all" onclick="tradeAllStock('${s.id}','sell')">Продать все · ${owned} шт.</button>`:''}</div><section class="corp-stock-info"><h2>Сведения</h2><div class="corp-stock-info-row"><span>Стоимость одной акции</span><strong>${fmt(s.current_price)}</strong></div><div class="corp-stock-info-row"><span>В портфеле</span><strong>${owned} шт.</strong></div><div class="corp-stock-info-row"><span>Дивиденды</span><strong>${Number(s.dividend_rate_percent||0).toFixed(2)}% / ч</strong></div><div class="corp-stock-description"><span>О компании</span><p>${s.description||'Описание компании пока отсутствует.'}</p></div></section></section>`;window.scrollTo({top:0,left:0,behavior:'auto'})}catch(e){corporationActiveStockId=null;modal('Ошибка',e.message);await renderInvestments()}};
window.openStock=openStock;

renderBondCard=function(b){const owned=Number(b.quantity||0),max=Math.floor(Number(state?.player?.money||0)/Number(b.price||1));return `<article class="card bond-card"><div class="business-head"><div><div class="stock-symbol">${b.symbol}</div><h3>${b.name}</h3><p>${b.description}</p></div><b>${fmt(b.price)}</b></div><div class="bond-yield">💰 Доходность: <b>${b.yield_rate_percent}% в час</b></div><div class="holding-row"><span>У тебя</span><b>${owned} шт.</b></div><div class="holding-row"><span>Доход</span><b>${fmt(b.income_hour)}/ч</b></div><div class="v20-action-grid"><button class="buy" onclick="openBondTrade('${b.id}','buy')">Купить</button><button class="v20-secondary" ${max>0?'':'disabled'} onclick="tradeAllBond('${b.id}','buy')">Купить на все · ${max}</button><button class="stock-sell" ${owned>0?'':'disabled'} onclick="openBondTrade('${b.id}','sell')">Продать</button><button class="v20-sell-all" ${owned>0?'':'disabled'} onclick="tradeAllBond('${b.id}','sell')">Продать все · ${owned}</button></div></article>`};
async function tradeAllBond(id,side){const b=bondsCache.find(x=>String(x.id)===String(id));if(!b)return;const qty=side==='buy'?Math.floor(Number(state.player.money||0)/Number(b.price||1)):Number(b.quantity||0);if(qty<=0){modal('Облигации',side==='buy'?'Недостаточно денег.':'У тебя нет этих облигаций.');return}if(!confirm(`${side==='buy'?'Купить на все свободные деньги':'Продать все'}: ${qty} шт. ${b.symbol}?`))return;try{const r=await api(`/api/bonds/${id}/${side}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quantity:qty})});state=r.state;bondsCache=r.bonds||await loadBonds();renderHeader();await renderInvestments();modal('Готово',`Количество: ${qty} шт.\nСумма: ${fmt(side==='buy'?r.total_cost:r.total_income)}`)}catch(e){modal('Операция не выполнена',e.message)}}
window.tradeAllBond=tradeAllBond;

renderRealEstate=async function(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Загружаем карту...</div>';try{const d=await api('/api/real-estate');realEstateCache=d.properties||[];const yields=realEstateCache.map(x=>Number(x.hourly_yield_percent||0)).filter(x=>x>0);const minY=yields.length?Math.min(...yields):0,maxY=yields.length?Math.max(...yields):0;c.innerHTML=`<section class="realestate-page"><div><div class="eyebrow">МИРОВАЯ НЕДВИЖИМОСТЬ</div><h2>🌍 Карта мира</h2><p class="section-note">Приближай карту и нажимай на маркеры городов.</p></div><div id="worldMap" class="world-map"></div><div class="realestate-summary"><span>🏠 Куплено объектов</span><b>${state.real_estate_count||0}</b><span>💰 Базовая доходность</span><b>${minY.toFixed(2)}–${maxY.toFixed(2)}% / ч</b></div></section>`;setTimeout(initWorldMap,0)}catch(e){modal('Недвижимость',e.message)}};

renderPropertyCard=function(p){const segmentNames={economy:'Эконом',business:'Бизнес',vip:'VIP'},typeNames={apartment:'Квартира',house:'Дом'};return `<article class="card property-card"><div class="property-image-wrap"><img src="${p.photo}" alt="${p.name}" loading="lazy" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src=propertyFallbackImage(p)"><div class="property-badges"><span class="segment-${p.segment||'economy'}">${segmentNames[p.segment]||'Эконом'}</span><span>${typeNames[p.property_type]||''}</span></div></div><div class="property-body"><div class="business-head"><div><h3>${p.name}</h3><p>${p.description}</p></div>${p.owned?'<b>✅ Куплено</b>':''}</div><div class="property-metrics"><div><span>${p.owned?'Рыночная стоимость':'Цена'}</span><b>${fmt(p.current_value)}</b></div><div><span>Аренда</span><b>${fmt(p.rent_hour)}/ч</b></div></div><div class="property-yield">Доходность аренды: <b>${Number(p.hourly_yield_percent||0).toFixed(2)}% / ч</b></div>${p.owned?`<div class="property-growth">📈 Полная капитализация с улучшениями: <b>${fmt(p.capitalization)}</b></div><div class="upgrade-grid">${p.upgrades.map(u=>`<button class="upgrade-btn ${u.owned?'owned':''}" ${u.owned?'disabled':''} onclick="upgradeProperty('${p.id}','${u.id}')"><b>${u.name}</b><span>${u.owned?'Установлено':`+${u.income_bonus_percent}% к аренде · ${fmt(u.cost)}`}</span></button>`).join('')}</div><button class="v20-property-sell" onclick="sellProperty('${p.id}')">Продать за 100% капитализации · ${fmt(p.sell_price)}</button>`:`<button class="buy" onclick="buyProperty('${p.id}')">Купить за ${fmt(p.purchase_price)}</button>`}</div></article>`};
async function sellProperty(id){const p=realEstateCache.find(x=>String(x.id)===String(id));if(!p||!p.owned)return;if(!confirm(`Продать ${p.name} за ${fmt(p.sell_price)}?`))return;try{const r=await api(`/api/real-estate/${id}/sell`,{method:'POST'});state=r.state;realEstateCache=r.properties;renderHeader();const next=realEstateCache.find(x=>x.id===id);openCity(next.city_id);modal('Недвижимость продана',`Получено ${fmt(r.sell_price)}.`)}catch(e){modal('Продажа не выполнена',e.message)}}
window.sellProperty=sellProperty;
window.renderStatistics=renderStatistics;window.renderRating=renderRating;window.openPlayerProfile=openPlayerProfile;window.renderRealEstate=renderRealEstate;window.renderPropertyCard=renderPropertyCard;window.renderBondCard=renderBondCard;
})();
